#!/bin/bash

# Instructions pour installer MongoDB sur différentes plateformes

echo "=== Guide d'installation de MongoDB ==="
echo ""
echo "1. UBUNTU/DEBIAN:"
echo "   sudo apt update"
echo "   sudo apt install -y mongodb"
echo "   sudo systemctl start mongodb"
echo "   sudo systemctl enable mongodb"
echo ""
echo "2. FEDORA/RHEL/CENTOS:"
echo "   sudo dnf install -y mongodb-org"
echo "   sudo systemctl start mongod"
echo "   sudo systemctl enable mongod"
echo ""
echo "3. MACOS (avec Homebrew):"
echo "   brew tap mongodb/brew"
echo "   brew install mongodb-community"
echo "   brew services start mongodb-community"
echo ""
echo "4. WINDOWS:"
echo "   Téléchargez l'installateur depuis https://www.mongodb.com/try/download/community"
echo "   Suivez les instructions d'installation"
echo "   MongoDB s'installera comme un service Windows"
echo ""
echo "5. DOCKER (alternative):"
echo "   docker pull mongo"
echo "   docker run -d -p 27017:27017 --name mongodb mongo"
echo ""
echo "Pour vérifier que MongoDB fonctionne, ouvrez un terminal et tapez:"
echo "   mongo --eval \"db.version()\""
echo "Vous devriez voir la version de MongoDB s'afficher."
